/*
  ============================================================
                         $RANDOM
  ============================================================

  - $random generates a pseudo-random 32-bit signed value.

        a = $random(2);

  - A seed can be provided to control the random sequence.


  ============================================================
                        $URANDOM
  ============================================================

  - $urandom generates a pseudo-random 32-bit unsigned value.

        b = $urandom(2);

  - A seed can be provided to control the random sequence.

  - Unlike $random, the value generated by $urandom is
    unsigned.


  ============================================================
                    $URANDOM_RANGE
  ============================================================

  - $urandom_range() generates a pseudo-random value within
    a specified range.

        $urandom_range(max, min);

  - In this example:

        c = $urandom_range(-1, -10);

  - The specified range is from -10 to -1.

  - The result is assigned to c, which is a 64-bit unsigned
    vector.

  ============================================================
                         SUMMARY
  ============================================================

  $random
      → 32-bit signed random value

  $urandom
      → 32-bit unsigned random value

  $urandom_range()
      → Random value within a specified range

  ============================================================
*/

module random_functions_tb;
  reg [63:0] a,b,c;
  initial begin
    a  = $random(2);  
    b  = $urandom(2); 
    c  = $urandom_range(-1,-10); 
    $display("a=%0d,a=%b",a,a);
    $display("b=%0d,b=%b",b,b);
    $display("c=%0d,c=%b",c,c);
  end 
endmodule

